# Generated by Django 5.1.4 on 2025-01-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='letter',
            field=models.CharField(choices=[('V', 'Visual'), ('A', 'Auditory'), ('R', 'Reading/Writing'), ('K', 'Kinesthetic')], default='V', max_length=1),
            preserve_default=False,
        ),
    ]
