# Generated by Django 4.2.18 on 2025-01-26 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_quizresult_auditory_quizresult_current_quiz_results_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='auditory',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='current_quiz_results',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='kinesthetic',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='reading_writing',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='total_questions',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='visual',
        ),
        migrations.CreateModel(
            name='AggregatedQuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(default=0)),
                ('visual', models.IntegerField(default=0)),
                ('auditory', models.IntegerField(default=0)),
                ('reading_writing', models.IntegerField(default=0)),
                ('kinesthetic', models.IntegerField(default=0)),
                ('current_quiz_results', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
