# Generated by Django 4.2.18 on 2025-01-26 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(choices=[('V', 'Visual'), ('A', 'Auditory'), ('R', 'Reading/Writing'), ('K', 'Kinesthetic')], max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.TextField()),
                ('link', models.URLField()),
                ('learning_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips.learningpattern')),
            ],
        ),
    ]
